import type { OverlayFormSchema } from "../../types.js";

export const ininjoSchema: OverlayFormSchema = {
  id: "ininjo",
  titleJa: "委任状",
  titleEn: "Letter of Authorization",
  pdfFilename: "ininjo.pdf",
  sourceUrl: "https://www.city.minato.tokyo.jp/documents/9717/ininjyou_1.pdf",
  category: "ward",
  jurisdiction: "minato-ku",
  lastVerifiedAt: "2026-04-15",
  fields: [
    {
      key: "application_year",
      x: 371,
      y: 493,
      width: 40,
      height: 28,
      labelEn: "Application Date",
      labelJa: "申請日",
    },
    {
      key: "application_month",
      x: 419,
      y: 482,
      width: 27,
      height: 50,
      labelEn: "Application Date",
      labelJa: "申請日",
    },
    {
      key: "application_day",
      x: 457,
      y: 488,
      width: 30,
      height: 36,
      labelEn: "Application Date",
      labelJa: "申請日",
    },
    {
      key: "proxy_address",
      x: 173,
      y: 403,
      width: 346,
      height: 19,
      labelEn: "Proxy Address",
      labelJa: "代理人の住所",
    },
    {
      key: "proxy_name",
      x: 173,
      y: 377,
      width: 347,
      height: 19,
      labelEn: "Proxy Name",
      labelJa: "代理人の氏名",
    },
    {
      key: "proxy_dob_year",
      x: 202,
      y: 349,
      width: 125,
      height: 19,
      labelEn: "Proxy Date of Birth",
      labelJa: "代理人の生年月日",
    },
    {
      key: "proxy_dob_month",
      x: 334,
      y: 344,
      width: 68,
      height: 30,
      labelEn: "Proxy Date of Birth",
      labelJa: "代理人の生年月日",
    },
    {
      key: "proxy_dob_day",
      x: 409,
      y: 344,
      width: 68,
      height: 30,
      labelEn: "Proxy Date of Birth",
      labelJa: "代理人の生年月日",
    },
    {
      key: "delegated_authority_summary",
      x: 193,
      y: 300,
      width: 350,
      height: 19,
      labelEn: "Delegated Authority Summary",
      labelJa: "委任項目",
    },
    {
      key: "delegated_authority_details",
      x: 63,
      y: 219,
      width: 489,
      height: 19,
      labelEn: "Delegated Authority Details",
      labelJa: "委任内容",
    },
    {
      key: "requester_address",
      x: 158,
      y: 179,
      width: 376,
      height: 19,
      labelEn: "Requester Address",
      labelJa: "請求者の住所",
    },
    {
      key: "requester_name",
      x: 158,
      y: 151,
      width: 307,
      height: 18,
      labelEn: "Requester Name",
      labelJa: "請求者の氏名",
    },
    {
      key: "requester_dob_year",
      x: 186,
      y: 124,
      width: 171,
      height: 18,
      labelEn: "Requester Date of Birth",
      labelJa: "請求者の生年月日",
    },
    {
      key: "requester_dob_month",
      x: 363,
      y: 118,
      width: 68,
      height: 30,
      labelEn: "Requester Date of Birth",
      labelJa: "請求者の生年月日",
    },
    {
      key: "requester_dob_day",
      x: 437,
      y: 118,
      width: 70,
      height: 30,
      labelEn: "Requester Date of Birth",
      labelJa: "請求者の生年月日",
    },
    {
      key: "requester_phone",
      x: 218,
      y: 98,
      width: 316,
      height: 19,
      labelEn: "Requester Phone",
      labelJa: "請求者の電話番号",
    },
  ],
};

// TODO: Fill in any remaining metadata placeholders before submitting.
// TODO: Verify every generated field against the blank PDF before submitting.
