import type { OverlayFormSchema } from "../../types.js";

export const teninSchema: OverlayFormSchema = {
  id: "tenin",
  titleJa: "転入届",
  titleEn: "Move-in notification",
  pdfFilename: "tenin.pdf",
  sourceUrl: "https://www.city.minato.tokyo.jp/",
  category: "ward",
  jurisdiction: "minato-ku",
  lastVerifiedAt: "2026-02-06",
  fields: [
    { key: "submit_year", x: 63, y: 519 },
    { key: "submit_month", x: 110, y: 519 },
    { key: "submit_day", x: 141, y: 519 },
    {
      key: "move_year",
      x: 204,
      y: 520,
      labelEn: "Move-in Date",
      labelJa: "転入日",
    },
    { key: "move_month", x: 257, y: 520 },
    { key: "move_day", x: 286, y: 520 },
    {
      key: "address",
      x: 113,
      y: 459,
      labelEn: "New Address",
      labelJa: "新住所",
    },
    {
      key: "furigana",
      x: 400,
      y: 461,
      labelEn: "Name (Katakana)",
      labelJa: "フリガナ",
    },
    {
      key: "name",
      x: 385,
      y: 444,
      labelEn: "Full Name",
      labelJa: "氏名",
    },
    { key: "phone", x: 597, y: 444, labelEn: "Phone", labelJa: "電話番号" },
    { key: "furigana_2", x: 69, y: 341 },
    { key: "name_2", x: 67, y: 318 },
    {
      key: "dob_year",
      x: 227,
      y: 320,
      labelEn: "Date of Birth",
      labelJa: "生年月日",
    },
    { key: "dob_month", x: 271, y: 320 },
    { key: "dob_day", x: 301, y: 320 },
  ],
};
